# Joker
import turtle
t = turtle.Pen()
t.speed(10)

def Eye():
    t.color("purple")
    t.fillcolor("purple")
    t.begin_fill()
    t.right(60)
    t.fd(50)
    t.left(120)
    t.fd(50)
    t.left(60)
    t.fd(50)
    t.left(120)
    t.fd(50)
    t.end_fill()
    t.left(110)
    t.goto(23,-10)
    t.fillcolor("black")
    t.begin_fill()
    t.circle(10)
    t.end_fill()

Eye()

def Eye2():
    t.color("purple")
    t.fillcolor("purple")
    t.begin_fill()
    t.right(60)
    t.fd(50)
    t.left(120)
    t.fd(50)
    t.left(60)
    t.fd(50)
    t.left(120)
    t.fd(50)
    t.end_fill()
    t.left(110)
    t.goto(123,-10)
    t.fillcolor("black")
    t.begin_fill()
    t.circle(10)
    t.end_fill()

def Joker():
    t.up()
    t.goto(100,0)
    t.left(10)
    Eye2()
    t.goto(50,-50)
    t.fd(20)
    t.fillcolor("red")
    t.begin_fill()
    t.circle(20)
    t.end_fill()
    t.up()
    t.goto(10,-60)
    t.down()
    t.begin_fill()
    t.left(10)
    t.right(100)
    t.circle(65,200)
    t.left(80)
    t.up()
    t.fd(128)
    t.down()
    t.left(106)
    t.circle(67,148)
    t.end_fill()
    t.hideturtle()
    turtle.done()
Joker()